name: untitled2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  noise_meter: ^3.0.1
  permission_handler: ^10.0.0
  speech_to_text: ^6.1.1
  fftea: ^1.0.0
  flutter_localization: ^0.1.10
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.2
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 6.0.0
  google_fonts: ^6.2.0
  intl: any
  json_path: 0.4.1
  mask_text_input_formatter: 2.4.0
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: 2.0.17
  shared_preferences_android: 2.1.0
  shared_preferences_foundation: 2.1.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: 2.1.0
  substring_highlight: 1.0.33
  timeago: 3.2.2
  url_launcher: 6.1.10
  audioplayers: ^5.0.0
  video_player: ^2.6.1
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11
  google_mlkit_pose_detection:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_pose_detection
  google_mlkit_image_labeling:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_image_labeling
  google_mlkit_face_detection:
    path: lib/vision_detector_views/mlkit_api_source/google_mlkit_face_detection
  flutter_screenutil: ^5.7.0
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.0.0+2
  file_picker: ^5.2.10
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.33
  fl_chart: ^0.62.0
  pytorch_mobile: ^0.2.2
  image: ^4.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  flutter_launcher_icons: 0.13.1

dependency_overrides:
  audio_streamer:
    path: packages/audio_streamer/audio_streamer-2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/picture/a.png
    - assets/picture/b.png
    - assets/pose_audios/upper/
    - assets/pose_audios/lower/
    - assets/pose_audios/
    - assets/ml/
    - assets/model/
    - assets/model/rsst_integrated_bi_1k2_wd_4_new_lite.pt

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.jpg"

